#!/bin/bash

echo "🚀 AFORSEV E-commerce Platform - Deployment Script"
echo "=================================================="

# Build frontend
echo "📦 Building frontend..."
cd frontend
npm run build
cd ..

echo ""
echo "✅ Build completed successfully!"
echo ""
echo "📋 DEPLOYMENT OPTIONS:"
echo ""
echo "Option 1: Quick Deploy to Vercel (Frontend) + Railway (Backend)"
echo "--------------------------------------------------------------"
echo "1. Push code to GitHub:"
echo "   git add . && git commit -m 'Ready for deployment' && git push"
echo ""
echo "2. Deploy backend to Railway:"
echo "   - Go to https://railway.app"
echo "   - New Project → Deploy from GitHub"
echo "   - Select backend folder"
echo "   - Add environment variables:"
echo "     DATABASE_URL=postgresql://..."
echo "     JWT_SECRET=your-secret-key"
echo "     PORT=3000"
echo ""
echo "3. Deploy frontend to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - New Project → Import from GitHub"
echo "   - Select frontend folder"
echo "   - Add environment variable:"
echo "     VITE_API_URL=https://your-backend.railway.app"
echo ""
echo "Option 2: Single Server Deployment"
echo "----------------------------------"
echo "1. Copy dist/ folder to your server"
echo "2. Install Node.js and npm"
echo "3. Run: npm install --production"
echo "4. Set up PM2: pm2 start npm --name 'backend' -- run start"
echo "5. Configure Nginx to serve frontend from /var/www/html"
echo ""
echo "📁 Production files ready in:"
echo "   - frontend/dist/ (frontend build)"
echo "   - backend/ (backend source)"
echo ""
echo "🌐 Test locally:"
echo "   Frontend: http://localhost:5173"
echo "   Backend:  http://localhost:3000"
echo ""
echo "🎯 Your project is ready for live deployment!"